#ifndef SMF_MEMORY_MAP_H
#define SMF_MEMORY_MAP_H

/*
 * Auto-generated Memory Map Header
 * Generated from: MMJ_ICD_021_IICD_06_Memory_map.xlsx
 * Generated at: 2025-07-27 20:54:05
 */
#define PACKET_SIZE 64

typedef struct {
    unsigned int32 used_size;
    unsigned int8 loop_counter;
    unsigned int8 reserved[3];
} partition_header_t;

// payloadに複数のpartition_headerを並べる
typedef union {
    unsigned int8 bytes[PACKET_SIZE];  // 生データアクセス用

    struct {
        union {
            struct {
                partition_header_t piclog;
                partition_header_t enviroment;
                partition_header_t iv_head;
                partition_header_t iv_data;
            }cigs;
            
            struct {
                partition_header_t piclog;
                partition_header_t enviroment;
                partition_header_t iv_head;
                partition_header_t iv_data;
            } satolab;
            // フラットにアクセスしたいとき用
            partition_header_t headers[(PACKET_SIZE - 1) / sizeof(partition_header_t)];
        } payload;

        unsigned int8 crc;  // 最後の1バイト
    };
} smf_data_table_t;

// Base Memory Configuration
#define SMF_SIZE 0x08000000 // 128MB
#define SMF_START_ADDRESS 0x00000000
#define SMF_END_ADDRESS   0x07FFFFFF


// ===== Device IDs from メモリマップ  =====
#define MAIN_DEVICE_ID 0x10
#define COM_DEVICE_ID 0x20
#define APRS_DEVICE_ID 0x60
#define CAM_DEVICE_ID 0x70
#define CHO_DEVICE_ID 0x80
#define SATO_DEVICE_ID 0x90
#define BHU_DEVICE_ID 0xB0
#define CIGS_DEVICE_ID 0xC0

// ===== Data IDs from メモリマップ  =====
#define ID_MAIN_ADDRESS_AREA 0x10
#define ID_MAIN_ADDRESS 0x11
#define ID_MAIN_RESERVED_COMMAND 0x12
#define ID_MAIN_HK 0x14
#define ID_MAIN_HSHK 0x15
#define ID_MAIN_LSHK 0x16
#define ID_MAIN_PIC_LOG 0x1F
#define ID_COM_RSSI_TRX_T_LOG 0x20
#define ID_COM_PIC_LOG 0x2F
#define ID_APRS_PIC_DATA_TABLE 0x60
#define ID_APRS_APRS 0x61
#define ID_APRS_IN_VEHICLE_COMMUNICATION_MISSION 0x62
#define ID_APRS_TLE_DATA 0x63
#define ID_APRS_ECOSYSTEM 0x67
#define ID_APRS_PIC_LOG 0x6F
#define ID_CAM_CHIBANY_THUMBNAIL_IMAGE_DATA_SIZE 0x70
#define ID_CAM_CHIBANY_IMAGE_DATA_SIZE 0x71
#define ID_CAM_CHIBANY_VIDEO_SIZE 0x72
#define ID_CAM_POLLEN_THUMBNAIL_IMAGE_DATA_SIZE 0x73
#define ID_CAM_POLEN_IMAGE_DATA_SIZE 0x74
#define ID_CAM_POLLEN_VIDEO_DATA_SIZE 0x75
#define ID_CAM_MCU_LOG_DATA_SIZE 0x7F
#define ID_CHO_GREECE_THUMBNAIL_IMAGE_DATA_SIZE 0x80
#define ID_CHO_GREECE_IMAGE_DATA_SIZE 0x81
#define ID_CHO_SENSOR_DATA_SIZE 0x82
#define ID_CHO_MCU_LOG_DATA_SIZE 0x8F
#define ID_SATO_PIC_DATA_TABLE 0x90
#define ID_SATO_CYCLE_MODE_DATA 0x91
#define ID_SATO_RANDOM_MODE_DATA 0x92
#define ID_SATO_MULTIPLE_POINT_MODE_DATA 0x93
#define ID_SATO_VOLTAGE_SWEEP_MODE_DATA 0x94
#define ID_SATO_PIC_LOG 0x9F
#define ID_BHU_FOREST_THUMBNAIL_IMAGE_DATA_SIZE 0xB0
#define ID_BHU_FOREST_IMAGE_DATA_SIZE 0xB1
#define ID_BHU_SENSOR_DATA_DATA_SIZE 0xB2
#define ID_BHU_MCU_LOG_DATA_SIZE 0xBF
#define ID_CIGS_DATA_TABLE 0xC0
#define ID_CIGS_MEASURE_DATA 0xC1
#define ID_CIGS_PICLOG 0xCF

// ===== Memory Address Mappings from メモリマップ  =====
#define MAIN_ADDRESS_AREA_START_ADDRESS 0x00000000
#define MAIN_ADDRESS_AREA_END_ADDRESS 0x00000FFF
#define MAIN_ADDRESS_START_ADDRESS 0x00001000
#define MAIN_ADDRESS_END_ADDRESS 0x00001FFF
#define MAIN_RESERVED_COMMAND_START_ADDRESS 0x00002000
#define MAIN_RESERVED_COMMAND_END_ADDRESS 0x00003FFF
#define MAIN_HK_START_ADDRESS 0x00004000
#define MAIN_HK_END_ADDRESS 0x02003FFF
#define MAIN_HSHK_START_ADDRESS 0x02004000
#define MAIN_HSHK_END_ADDRESS 0x02103FFF
#define MAIN_LSHK_START_ADDRESS 0x02104000
#define MAIN_LSHK_END_ADDRESS 0x02303FFF
#define MAIN_PIC_LOG_START_ADDRESS 0x02304000
#define MAIN_PIC_LOG_END_ADDRESS 0x0240FFFF
#define COM_RSSI_TRX_T_LOG_START_ADDRESS 0x02800000
#define COM_RSSI_TRX_T_LOG_END_ADDRESS 0x028FFFFF
#define COM_PIC_LOG_START_ADDRESS 0x02900000
#define COM_PIC_LOG_END_ADDRESS 0x029FFFFF
#define APRS_PIC_DATA_TABLE_START_ADDRESS 0x02C00000
#define APRS_PIC_DATA_TABLE_END_ADDRESS 0x02C00FFF
#define APRS_APRS_START_ADDRESS 0x02C01000
#define APRS_APRS_END_ADDRESS 0x02D00FFF
#define APRS_IN_VEHICLE_COMMUNICATION_MISSION_START_ADDRESS 0x02D01000
#define APRS_IN_VEHICLE_COMMUNICATION_MISSION_END_ADDRESS 0x02D01FFF
#define APRS_TLE_DATA_START_ADDRESS 0x02D02000
#define APRS_TLE_DATA_END_ADDRESS 0x02D02FFF
#define APRS_ECOSYSTEM_START_ADDRESS 0x02D03000
#define APRS_ECOSYSTEM_END_ADDRESS 0x02E02FFF
#define APRS_PIC_LOG_START_ADDRESS 0x02E03000
#define APRS_PIC_LOG_END_ADDRESS 0x02E03FFF
#define CAM_CHIBANY_THUMBNAIL_IMAGE_DATA_SIZE_START_ADDRESS 0x02F10000
#define CAM_CHIBANY_THUMBNAIL_IMAGE_DATA_SIZE_END_ADDRESS 0x02F10FFF
#define CAM_CHIBANY_IMAGE_DATA_SIZE_START_ADDRESS 0x03311000
#define CAM_CHIBANY_IMAGE_DATA_SIZE_END_ADDRESS 0x03311FFF
#define CAM_CHIBANY_VIDEO_SIZE_START_ADDRESS 0x03712000
#define CAM_CHIBANY_VIDEO_SIZE_END_ADDRESS 0x03712FFF
#define CAM_POLLEN_THUMBNAIL_IMAGE_DATA_SIZE_START_ADDRESS 0x03B13000
#define CAM_POLLEN_THUMBNAIL_IMAGE_DATA_SIZE_END_ADDRESS 0x03B13FFF
#define CAM_POLEN_IMAGE_DATA_SIZE_START_ADDRESS 0x03F14000
#define CAM_POLEN_IMAGE_DATA_SIZE_END_ADDRESS 0x03F14FFF
#define CAM_POLLEN_VIDEO_DATA_SIZE_START_ADDRESS 0x04315000
#define CAM_POLLEN_VIDEO_DATA_SIZE_END_ADDRESS 0x04315FFF
#define CAM_MCU_LOG_DATA_SIZE_START_ADDRESS 0x04320000
#define CAM_MCU_LOG_DATA_SIZE_END_ADDRESS 0x04320FFF
#define CHO_GREECE_THUMBNAIL_IMAGE_DATA_SIZE_START_ADDRESS 0x04440000
#define CHO_GREECE_THUMBNAIL_IMAGE_DATA_SIZE_END_ADDRESS 0x04440FFF
#define CHO_GREECE_IMAGE_DATA_SIZE_START_ADDRESS 0x04451000
#define CHO_GREECE_IMAGE_DATA_SIZE_END_ADDRESS 0x04451FFF
#define CHO_SENSOR_DATA_SIZE_START_ADDRESS 0x04852000
#define CHO_SENSOR_DATA_SIZE_END_ADDRESS 0x04852FFF
#define CHO_MCU_LOG_DATA_SIZE_START_ADDRESS 0x04863000
#define CHO_MCU_LOG_DATA_SIZE_END_ADDRESS 0x04863FFF
#define SATO_PIC_DATA_TABLE_START_ADDRESS 0x04980000
#define SATO_PIC_DATA_TABLE_END_ADDRESS 0x04980FFF
#define SATO_CYCLE_MODE_DATA_START_ADDRESS 0x04981000
#define SATO_CYCLE_MODE_DATA_END_ADDRESS 0x04A80FFF
#define SATO_RANDOM_MODE_DATA_START_ADDRESS 0x04A81000
#define SATO_RANDOM_MODE_DATA_END_ADDRESS 0x04E80FFF
#define SATO_MULTIPLE_POINT_MODE_DATA_START_ADDRESS 0x04E81000
#define SATO_MULTIPLE_POINT_MODE_DATA_END_ADDRESS 0x04F80FFF
#define SATO_VOLTAGE_SWEEP_MODE_DATA_START_ADDRESS 0x04F81000
#define SATO_VOLTAGE_SWEEP_MODE_DATA_END_ADDRESS 0x05080FFF
#define SATO_PIC_LOG_START_ADDRESS 0x05081000
#define SATO_PIC_LOG_END_ADDRESS 0x05081FFF
#define BHU_FOREST_THUMBNAIL_IMAGE_DATA_SIZE_START_ADDRESS 0x05190000
#define BHU_FOREST_THUMBNAIL_IMAGE_DATA_SIZE_END_ADDRESS 0x05190FFF
#define BHU_FOREST_IMAGE_DATA_SIZE_START_ADDRESS 0x05591000
#define BHU_FOREST_IMAGE_DATA_SIZE_END_ADDRESS 0x05591FFF
#define BHU_SENSOR_DATA_DATA_SIZE_START_ADDRESS 0x05992000
#define BHU_SENSOR_DATA_DATA_SIZE_END_ADDRESS 0x05992FFF
#define BHU_MCU_LOG_DATA_SIZE_START_ADDRESS 0x06993000
#define BHU_MCU_LOG_DATA_SIZE_END_ADDRESS 0x06993FFF
#define CIGS_DATA_TABLE_START_ADDRESS 0x06AA0000
#define CIGS_DATA_TABLE_END_ADDRESS 0x06AA0FFF
#define CIGS_MEASURE_DATA_START_ADDRESS 0x06AA1000
#define CIGS_MEASURE_DATA_END_ADDRESS 0x07AA0FFF
#define CIGS_PICLOG_START_ADDRESS 0x07AA1000
#define CIGS_PICLOG_END_ADDRESS 0x07AA1FFF

#endif // SMF_MEMORY_MAP_H
